name: "SpotDL Webserver"
version: "0.0.64"
slug: "spotdl"
description: "A web server to use SpotDL for downloading Spotify songs."
url: "https://github.com/spotDL/spotify-downloader"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ingress: true
ingress_port: 6544
map:
  - "share:rw"
  - "media:rw"
panel_icon: mdi:spotify

options:
  SOCKETIO_PATH: "/hassio/ingress/a914fd44_spotdl/socket.io"
  TRACK_OUTPUT: "/media"
  ALBUM_OUTPUT: "/media"
  PLAYLIST_OUTPUT: "/media"
  ARTIST_OUTPUT: "/media"
  ABSOLUTE_SERVER_PATH: "/media"
  M3U_PLAYLIST_PATH: "/media"

schema:
  SOCKETIO_PATH: str?
  TRACK_OUTPUT: str?
  ALBUM_OUTPUT: str?
  PLAYLIST_OUTPUT: str?
  ARTIST_OUTPUT: str?
  ABSOLUTE_SERVER_PATH: str?
  M3U_PLAYLIST_PATH: str?

legacy: true
