name: "SpotDL Webserver"
version: "0.0.33"
slug: "spotdl"
description: "A web server to use SpotDL for downloading Spotify songs."
url: "https://github.com/spotDL/spotify-downloader"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
ingress: true
ingress_port: 5000
map:
  - "share:rw"
  - "media:rw"
panel_icon: mdi:spotify
